defaults:
  - _self_
  - env: cartpole
  - alg: shac

exp_name: shac_benchmarks

id: ${hydra.job.id}
resume_model: null

general:
  play: False
  logdir: logs/${alg.name}/${env.name}/
  save_interval: False
  no_time_stamp: False
  render: False
  device: cuda:0
  run_wandb: True
  seed: 0
  train: True
  checkpoint:
  multi_gpu: False
  mixed_precision: False


# env-specific defaults for different algs
env:
  gamma: 0.99
  player:
    games_num: 12
    num_actors: 4

  shac:
    lambda: 0.95
    actor_mlp:
      units:
        - 64
        - 64
    critic_mlp:
      units:
        - 64
        - 64
    target_critic_alpha: 0.4
    actor_lr: 1e-3
    critic_lr: 1e-3
    max_epochs: 2000
    save_interval: 400
    steps_num: 32
    betas: 
      - 0.7
      - 0.95

  shac2: ${.shac}

wandb:
  project: shac
  group: ${exp_name}
  sweep_name_prefix: ${alg.params.config.name}-run
