name: df_ant
config:
  _target_: shac.envs.AntEnv
  render: ${general.render}
  device: ${general.device}
  num_envs: ${resolve_default:512,${general.num_envs}}
  stochastic_init: True
  seed: ${general.seed}
  no_grad: ${general.play}
  episode_length: 1000
  MM_caching_frequency: 16
  early_termination: True

actor_mlp:
  units: [128, 64, 64]

shac:
  actor_lr: 2e-3
  critic_lr: 2e-3
  max_epochs: 2000
  num_actors: 64
  target_critic_alpha: 0.2
