name: df_anymal
config:
  _target_: shac.envs.AnymalEnv
  render: ${general.render}
  device: ${general.device}
  num_envs: 512
  stochastic_init: True
  seed: ${general.seed}
  no_grad: ??? # decided based on algorithm
  episode_length: 1000
  MM_caching_frequency: 16
  early_termination: True

shac:
  actor_lr: 2e-3
  critic_lr: 2e-3
  max_epochs: 2000
  target_critic_alpha: 0.2
  actor_mlp:
    units: [256, 128]
  critic_mlp:
    units: [256, 128]

ppo:
  max_epochs: 5000
  minibatch_size: 8192
  num_actors: 1024
  horizon_length: 32
  save_frequency: 500
  save_best_after: 500
  actor_mlp:
    units: [128, 64, 32]
  critic_mlp:
    units: [128, 64, 32]

svg:
  num_train_steps: 
