name: warp_cartpole
config:
  _target_: shac.envs.CartPoleSwingUpWarpEnv
  render: ${general.render}
  device: ${general.device}
  num_envs: 1024
  seed: ${general.seed}
  episode_length: 240
  no_grad: ${general.play}
  stochastic_init: False
  early_termination: False

actor_lr: 1e-3
critic_lr: 1e-2
max_epochs: 500
save_interval: 100

player:
  games_num: 4
  num_actors: 4
