name: warp_claw
config:
  _target_: dmanip.envs.ClawWarpEnv
  config:
    _target_: dmanip.config.ClawWarpConfig
    render: ${general.render}
    device: ${general.device}
    no_grad: ??? # decided based on algorithm
    seed: ${general.seed}
    episode_length: 240
    no_grad: ${general.play}
    stochastic_init: False
    rew_kw:
      _target_: dmanip.config.RewardConfig
      c_finger: 0.2
      c_q: 100
      c_act: 0.

shac:
  actor_lr: 1e-3
  critic_lr: 1e-2
  max_epochs: 500
  betas: (0.7, 0.95)

ppo:
  max_epochs: 500
  minibatch_size: 1920
  save_interval: 100
  save_best_after: 50
  num_actors: 32
  steps_num: 240

player:
  games_num: 12
  num_actors: 4
