_target_: shac.envs.DoublePendulumEnv
render: ${general.render}
device: ${general.device}
num_envs: 1024
seed: ${general.seed}
episode_length: 200
no_grad: False
stochastic_init: False
MM_caching_frequency: 4
early_termination: False
