_target_: warp.envs.hopper.HopperEnv
render: ${general.render}
device: ${general.device}
num_envs: 1024
seed: ${general.seed}
episode_length: 200
no_grad: False
stochastic_init: False
# early_termination: False
ag_return_body: True
