name: df_hopper
 
config:
  _target_: shac.envs.HopperEnv
  render: ${general.render}
  device: ${general.device}
  num_envs: ${resolve_default:256,${general.num_envs}}
  seed: ${general.seed}
  episode_length: 1000
  no_grad: ${general.play}
  stochastic_init: True
  MM_caching_frequency: 4
  early_termination: True
  contact_ke: 2e4
  contact_kd: 1e3
    
shac:
  actor_lr: 2e-3
  critic_lr: 2e-4
  max_epochs: 2000
  betas:
    - 0.7
    - 0.95
  actor_mlp:
    units: 
      - 128
      - 64
      - 32
  critic_mlp:
    units:
      - 64
      - 64
  save_interval: 400

ppo:
  max_epochs: 2000 
  minibatch_size: 8192
  save_interval: 400
  save_best_after: 100
  num_actors: 1024
  steps_num: 240
  actor_mlp:
    units: 
      - 128
      - 64
      - 32
  critic_mlp:
    units:
      - 64
      - 64



player:
  games_num: 1
  num_actors: 1
